// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: original_images.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOriginalImage = `-- name: CreateOriginalImage :one
INSERT INTO original_images (
  content_hash, s3_key, file_size, mime_type, width, height, reference_count
) VALUES (
  $1, $2, $3, $4, $5, $6, 1
) RETURNING id, content_hash, s3_key, file_size, mime_type, width, height, reference_count, created_at, updated_at
`

type CreateOriginalImageParams struct {
	ContentHash string      `json:"content_hash"`
	S3Key       string      `json:"s3_key"`
	FileSize    int64       `json:"file_size"`
	MimeType    string      `json:"mime_type"`
	Width       pgtype.Int4 `json:"width"`
	Height      pgtype.Int4 `json:"height"`
}

func (q *Queries) CreateOriginalImage(ctx context.Context, arg CreateOriginalImageParams) (*OriginalImage, error) {
	row := q.db.QueryRow(ctx, CreateOriginalImage,
		arg.ContentHash,
		arg.S3Key,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
	)
	var i OriginalImage
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.S3Key,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.ReferenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DecrementReferenceCount = `-- name: DecrementReferenceCount :exec
UPDATE original_images
SET reference_count = GREATEST(reference_count - 1, 0),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) DecrementReferenceCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DecrementReferenceCount, id)
	return err
}

const DeleteOriginalImage = `-- name: DeleteOriginalImage :exec
DELETE FROM original_images
WHERE id = $1
`

func (q *Queries) DeleteOriginalImage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOriginalImage, id)
	return err
}

const GetOriginalImageByHash = `-- name: GetOriginalImageByHash :one
SELECT id, content_hash, s3_key, file_size, mime_type, width, height, reference_count, created_at, updated_at FROM original_images
WHERE content_hash = $1
`

func (q *Queries) GetOriginalImageByHash(ctx context.Context, contentHash string) (*OriginalImage, error) {
	row := q.db.QueryRow(ctx, GetOriginalImageByHash, contentHash)
	var i OriginalImage
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.S3Key,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.ReferenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetOriginalImageByID = `-- name: GetOriginalImageByID :one
SELECT id, content_hash, s3_key, file_size, mime_type, width, height, reference_count, created_at, updated_at FROM original_images
WHERE id = $1
`

func (q *Queries) GetOriginalImageByID(ctx context.Context, id pgtype.UUID) (*OriginalImage, error) {
	row := q.db.QueryRow(ctx, GetOriginalImageByID, id)
	var i OriginalImage
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.S3Key,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.ReferenceCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetOriginalImageStats = `-- name: GetOriginalImageStats :one
SELECT 
  COUNT(*) as total_count,
  SUM(file_size) as total_size,
  SUM(CASE WHEN reference_count = 0 THEN 1 ELSE 0 END) as orphaned_count,
  SUM(CASE WHEN reference_count = 0 THEN file_size ELSE 0 END) as orphaned_size,
  AVG(reference_count) as avg_references
FROM original_images
`

type GetOriginalImageStatsRow struct {
	TotalCount    int64   `json:"total_count"`
	TotalSize     int64   `json:"total_size"`
	OrphanedCount int64   `json:"orphaned_count"`
	OrphanedSize  int64   `json:"orphaned_size"`
	AvgReferences float64 `json:"avg_references"`
}

func (q *Queries) GetOriginalImageStats(ctx context.Context) (*GetOriginalImageStatsRow, error) {
	row := q.db.QueryRow(ctx, GetOriginalImageStats)
	var i GetOriginalImageStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.TotalSize,
		&i.OrphanedCount,
		&i.OrphanedSize,
		&i.AvgReferences,
	)
	return &i, err
}

const IncrementReferenceCount = `-- name: IncrementReferenceCount :exec
UPDATE original_images
SET reference_count = reference_count + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementReferenceCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, IncrementReferenceCount, id)
	return err
}

const ListOrphanedOriginalImages = `-- name: ListOrphanedOriginalImages :many
SELECT id, content_hash, s3_key, file_size, mime_type, width, height, reference_count, created_at, updated_at FROM original_images
WHERE reference_count = 0
  AND updated_at < (NOW() - $1::interval)
ORDER BY updated_at ASC
LIMIT $2
`

type ListOrphanedOriginalImagesParams struct {
	Column1 pgtype.Interval `json:"column_1"`
	Limit   int32           `json:"limit"`
}

func (q *Queries) ListOrphanedOriginalImages(ctx context.Context, arg ListOrphanedOriginalImagesParams) ([]*OriginalImage, error) {
	rows, err := q.db.Query(ctx, ListOrphanedOriginalImages, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OriginalImage{}
	for rows.Next() {
		var i OriginalImage
		if err := rows.Scan(
			&i.ID,
			&i.ContentHash,
			&i.S3Key,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.ReferenceCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
