// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"github.com/labstack/echo/v4"
	"sync"
)

// Ensure, that HandlerMock does implement Handler.
// If this is not the case, regenerate this file with moq.
var _ Handler = &HandlerMock{}

// HandlerMock is a mock implementation of Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked Handler
//		mockedHandler := &HandlerMock{
//			GetActiveModelFunc: func(c echo.Context) error {
//				panic("mock out the GetActiveModel method")
//			},
//			GetModelConfigFunc: func(c echo.Context) error {
//				panic("mock out the GetModelConfig method")
//			},
//			GetModelConfigSchemaFunc: func(c echo.Context) error {
//				panic("mock out the GetModelConfigSchema method")
//			},
//			GetSettingFunc: func(c echo.Context) error {
//				panic("mock out the GetSetting method")
//			},
//			ListModelsFunc: func(c echo.Context) error {
//				panic("mock out the ListModels method")
//			},
//			ListSettingsFunc: func(c echo.Context) error {
//				panic("mock out the ListSettings method")
//			},
//			UpdateActiveModelFunc: func(c echo.Context) error {
//				panic("mock out the UpdateActiveModel method")
//			},
//			UpdateModelConfigFunc: func(c echo.Context) error {
//				panic("mock out the UpdateModelConfig method")
//			},
//			UpdateSettingFunc: func(c echo.Context) error {
//				panic("mock out the UpdateSetting method")
//			},
//			resolveUserUUIDFunc: func(c echo.Context) (string, error) {
//				panic("mock out the resolveUserUUID method")
//			},
//		}
//
//		// use mockedHandler in code that requires Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// GetActiveModelFunc mocks the GetActiveModel method.
	GetActiveModelFunc func(c echo.Context) error

	// GetModelConfigFunc mocks the GetModelConfig method.
	GetModelConfigFunc func(c echo.Context) error

	// GetModelConfigSchemaFunc mocks the GetModelConfigSchema method.
	GetModelConfigSchemaFunc func(c echo.Context) error

	// GetSettingFunc mocks the GetSetting method.
	GetSettingFunc func(c echo.Context) error

	// ListModelsFunc mocks the ListModels method.
	ListModelsFunc func(c echo.Context) error

	// ListSettingsFunc mocks the ListSettings method.
	ListSettingsFunc func(c echo.Context) error

	// UpdateActiveModelFunc mocks the UpdateActiveModel method.
	UpdateActiveModelFunc func(c echo.Context) error

	// UpdateModelConfigFunc mocks the UpdateModelConfig method.
	UpdateModelConfigFunc func(c echo.Context) error

	// UpdateSettingFunc mocks the UpdateSetting method.
	UpdateSettingFunc func(c echo.Context) error

	// resolveUserUUIDFunc mocks the resolveUserUUID method.
	resolveUserUUIDFunc func(c echo.Context) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetActiveModel holds details about calls to the GetActiveModel method.
		GetActiveModel []struct {
			// C is the c argument value.
			C echo.Context
		}
		// GetModelConfig holds details about calls to the GetModelConfig method.
		GetModelConfig []struct {
			// C is the c argument value.
			C echo.Context
		}
		// GetModelConfigSchema holds details about calls to the GetModelConfigSchema method.
		GetModelConfigSchema []struct {
			// C is the c argument value.
			C echo.Context
		}
		// GetSetting holds details about calls to the GetSetting method.
		GetSetting []struct {
			// C is the c argument value.
			C echo.Context
		}
		// ListModels holds details about calls to the ListModels method.
		ListModels []struct {
			// C is the c argument value.
			C echo.Context
		}
		// ListSettings holds details about calls to the ListSettings method.
		ListSettings []struct {
			// C is the c argument value.
			C echo.Context
		}
		// UpdateActiveModel holds details about calls to the UpdateActiveModel method.
		UpdateActiveModel []struct {
			// C is the c argument value.
			C echo.Context
		}
		// UpdateModelConfig holds details about calls to the UpdateModelConfig method.
		UpdateModelConfig []struct {
			// C is the c argument value.
			C echo.Context
		}
		// UpdateSetting holds details about calls to the UpdateSetting method.
		UpdateSetting []struct {
			// C is the c argument value.
			C echo.Context
		}
		// resolveUserUUID holds details about calls to the resolveUserUUID method.
		resolveUserUUID []struct {
			// C is the c argument value.
			C echo.Context
		}
	}
	lockGetActiveModel       sync.RWMutex
	lockGetModelConfig       sync.RWMutex
	lockGetModelConfigSchema sync.RWMutex
	lockGetSetting           sync.RWMutex
	lockListModels           sync.RWMutex
	lockListSettings         sync.RWMutex
	lockUpdateActiveModel    sync.RWMutex
	lockUpdateModelConfig    sync.RWMutex
	lockUpdateSetting        sync.RWMutex
	lockresolveUserUUID      sync.RWMutex
}

// GetActiveModel calls GetActiveModelFunc.
func (mock *HandlerMock) GetActiveModel(c echo.Context) error {
	if mock.GetActiveModelFunc == nil {
		panic("HandlerMock.GetActiveModelFunc: method is nil but Handler.GetActiveModel was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockGetActiveModel.Lock()
	mock.calls.GetActiveModel = append(mock.calls.GetActiveModel, callInfo)
	mock.lockGetActiveModel.Unlock()
	return mock.GetActiveModelFunc(c)
}

// GetActiveModelCalls gets all the calls that were made to GetActiveModel.
// Check the length with:
//
//	len(mockedHandler.GetActiveModelCalls())
func (mock *HandlerMock) GetActiveModelCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockGetActiveModel.RLock()
	calls = mock.calls.GetActiveModel
	mock.lockGetActiveModel.RUnlock()
	return calls
}

// GetModelConfig calls GetModelConfigFunc.
func (mock *HandlerMock) GetModelConfig(c echo.Context) error {
	if mock.GetModelConfigFunc == nil {
		panic("HandlerMock.GetModelConfigFunc: method is nil but Handler.GetModelConfig was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockGetModelConfig.Lock()
	mock.calls.GetModelConfig = append(mock.calls.GetModelConfig, callInfo)
	mock.lockGetModelConfig.Unlock()
	return mock.GetModelConfigFunc(c)
}

// GetModelConfigCalls gets all the calls that were made to GetModelConfig.
// Check the length with:
//
//	len(mockedHandler.GetModelConfigCalls())
func (mock *HandlerMock) GetModelConfigCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockGetModelConfig.RLock()
	calls = mock.calls.GetModelConfig
	mock.lockGetModelConfig.RUnlock()
	return calls
}

// GetModelConfigSchema calls GetModelConfigSchemaFunc.
func (mock *HandlerMock) GetModelConfigSchema(c echo.Context) error {
	if mock.GetModelConfigSchemaFunc == nil {
		panic("HandlerMock.GetModelConfigSchemaFunc: method is nil but Handler.GetModelConfigSchema was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockGetModelConfigSchema.Lock()
	mock.calls.GetModelConfigSchema = append(mock.calls.GetModelConfigSchema, callInfo)
	mock.lockGetModelConfigSchema.Unlock()
	return mock.GetModelConfigSchemaFunc(c)
}

// GetModelConfigSchemaCalls gets all the calls that were made to GetModelConfigSchema.
// Check the length with:
//
//	len(mockedHandler.GetModelConfigSchemaCalls())
func (mock *HandlerMock) GetModelConfigSchemaCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockGetModelConfigSchema.RLock()
	calls = mock.calls.GetModelConfigSchema
	mock.lockGetModelConfigSchema.RUnlock()
	return calls
}

// GetSetting calls GetSettingFunc.
func (mock *HandlerMock) GetSetting(c echo.Context) error {
	if mock.GetSettingFunc == nil {
		panic("HandlerMock.GetSettingFunc: method is nil but Handler.GetSetting was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockGetSetting.Lock()
	mock.calls.GetSetting = append(mock.calls.GetSetting, callInfo)
	mock.lockGetSetting.Unlock()
	return mock.GetSettingFunc(c)
}

// GetSettingCalls gets all the calls that were made to GetSetting.
// Check the length with:
//
//	len(mockedHandler.GetSettingCalls())
func (mock *HandlerMock) GetSettingCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockGetSetting.RLock()
	calls = mock.calls.GetSetting
	mock.lockGetSetting.RUnlock()
	return calls
}

// ListModels calls ListModelsFunc.
func (mock *HandlerMock) ListModels(c echo.Context) error {
	if mock.ListModelsFunc == nil {
		panic("HandlerMock.ListModelsFunc: method is nil but Handler.ListModels was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockListModels.Lock()
	mock.calls.ListModels = append(mock.calls.ListModels, callInfo)
	mock.lockListModels.Unlock()
	return mock.ListModelsFunc(c)
}

// ListModelsCalls gets all the calls that were made to ListModels.
// Check the length with:
//
//	len(mockedHandler.ListModelsCalls())
func (mock *HandlerMock) ListModelsCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockListModels.RLock()
	calls = mock.calls.ListModels
	mock.lockListModels.RUnlock()
	return calls
}

// ListSettings calls ListSettingsFunc.
func (mock *HandlerMock) ListSettings(c echo.Context) error {
	if mock.ListSettingsFunc == nil {
		panic("HandlerMock.ListSettingsFunc: method is nil but Handler.ListSettings was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockListSettings.Lock()
	mock.calls.ListSettings = append(mock.calls.ListSettings, callInfo)
	mock.lockListSettings.Unlock()
	return mock.ListSettingsFunc(c)
}

// ListSettingsCalls gets all the calls that were made to ListSettings.
// Check the length with:
//
//	len(mockedHandler.ListSettingsCalls())
func (mock *HandlerMock) ListSettingsCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockListSettings.RLock()
	calls = mock.calls.ListSettings
	mock.lockListSettings.RUnlock()
	return calls
}

// UpdateActiveModel calls UpdateActiveModelFunc.
func (mock *HandlerMock) UpdateActiveModel(c echo.Context) error {
	if mock.UpdateActiveModelFunc == nil {
		panic("HandlerMock.UpdateActiveModelFunc: method is nil but Handler.UpdateActiveModel was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockUpdateActiveModel.Lock()
	mock.calls.UpdateActiveModel = append(mock.calls.UpdateActiveModel, callInfo)
	mock.lockUpdateActiveModel.Unlock()
	return mock.UpdateActiveModelFunc(c)
}

// UpdateActiveModelCalls gets all the calls that were made to UpdateActiveModel.
// Check the length with:
//
//	len(mockedHandler.UpdateActiveModelCalls())
func (mock *HandlerMock) UpdateActiveModelCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockUpdateActiveModel.RLock()
	calls = mock.calls.UpdateActiveModel
	mock.lockUpdateActiveModel.RUnlock()
	return calls
}

// UpdateModelConfig calls UpdateModelConfigFunc.
func (mock *HandlerMock) UpdateModelConfig(c echo.Context) error {
	if mock.UpdateModelConfigFunc == nil {
		panic("HandlerMock.UpdateModelConfigFunc: method is nil but Handler.UpdateModelConfig was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockUpdateModelConfig.Lock()
	mock.calls.UpdateModelConfig = append(mock.calls.UpdateModelConfig, callInfo)
	mock.lockUpdateModelConfig.Unlock()
	return mock.UpdateModelConfigFunc(c)
}

// UpdateModelConfigCalls gets all the calls that were made to UpdateModelConfig.
// Check the length with:
//
//	len(mockedHandler.UpdateModelConfigCalls())
func (mock *HandlerMock) UpdateModelConfigCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockUpdateModelConfig.RLock()
	calls = mock.calls.UpdateModelConfig
	mock.lockUpdateModelConfig.RUnlock()
	return calls
}

// UpdateSetting calls UpdateSettingFunc.
func (mock *HandlerMock) UpdateSetting(c echo.Context) error {
	if mock.UpdateSettingFunc == nil {
		panic("HandlerMock.UpdateSettingFunc: method is nil but Handler.UpdateSetting was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockUpdateSetting.Lock()
	mock.calls.UpdateSetting = append(mock.calls.UpdateSetting, callInfo)
	mock.lockUpdateSetting.Unlock()
	return mock.UpdateSettingFunc(c)
}

// UpdateSettingCalls gets all the calls that were made to UpdateSetting.
// Check the length with:
//
//	len(mockedHandler.UpdateSettingCalls())
func (mock *HandlerMock) UpdateSettingCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockUpdateSetting.RLock()
	calls = mock.calls.UpdateSetting
	mock.lockUpdateSetting.RUnlock()
	return calls
}

// resolveUserUUID calls resolveUserUUIDFunc.
func (mock *HandlerMock) resolveUserUUID(c echo.Context) (string, error) {
	if mock.resolveUserUUIDFunc == nil {
		panic("HandlerMock.resolveUserUUIDFunc: method is nil but Handler.resolveUserUUID was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockresolveUserUUID.Lock()
	mock.calls.resolveUserUUID = append(mock.calls.resolveUserUUID, callInfo)
	mock.lockresolveUserUUID.Unlock()
	return mock.resolveUserUUIDFunc(c)
}

// resolveUserUUIDCalls gets all the calls that were made to resolveUserUUID.
// Check the length with:
//
//	len(mockedHandler.resolveUserUUIDCalls())
func (mock *HandlerMock) resolveUserUUIDCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockresolveUserUUID.RLock()
	calls = mock.calls.resolveUserUUID
	mock.lockresolveUserUUID.RUnlock()
	return calls
}
