// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdn

import (
	"github.com/labstack/echo/v4"
	"sync"
)

// Ensure, that HandlerMock does implement Handler.
// If this is not the case, regenerate this file with moq.
var _ Handler = &HandlerMock{}

// HandlerMock is a mock implementation of Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked Handler
//		mockedHandler := &HandlerMock{
//			ProxyImageFunc: func(c echo.Context) error {
//				panic("mock out the ProxyImage method")
//			},
//		}
//
//		// use mockedHandler in code that requires Handler
//		// and then make assertions.
//
//	}
type HandlerMock struct {
	// ProxyImageFunc mocks the ProxyImage method.
	ProxyImageFunc func(c echo.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// ProxyImage holds details about calls to the ProxyImage method.
		ProxyImage []struct {
			// C is the c argument value.
			C echo.Context
		}
	}
	lockProxyImage sync.RWMutex
}

// ProxyImage calls ProxyImageFunc.
func (mock *HandlerMock) ProxyImage(c echo.Context) error {
	if mock.ProxyImageFunc == nil {
		panic("HandlerMock.ProxyImageFunc: method is nil but Handler.ProxyImage was just called")
	}
	callInfo := struct {
		C echo.Context
	}{
		C: c,
	}
	mock.lockProxyImage.Lock()
	mock.calls.ProxyImage = append(mock.calls.ProxyImage, callInfo)
	mock.lockProxyImage.Unlock()
	return mock.ProxyImageFunc(c)
}

// ProxyImageCalls gets all the calls that were made to ProxyImage.
// Check the length with:
//
//	len(mockedHandler.ProxyImageCalls())
func (mock *HandlerMock) ProxyImageCalls() []struct {
	C echo.Context
} {
	var calls []struct {
		C echo.Context
	}
	mock.lockProxyImage.RLock()
	calls = mock.calls.ProxyImage
	mock.lockProxyImage.RUnlock()
	return calls
}
