// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package originalimage

import (
	"context"
	"github.com/real-staging-ai/api/internal/storage/queries"
	"sync"
	"time"
)

// Ensure, that RepositoryMock does implement Repository.
// If this is not the case, regenerate this file with moq.
var _ Repository = &RepositoryMock{}

// RepositoryMock is a mock implementation of Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked Repository
//		mockedRepository := &RepositoryMock{
//			CreateOriginalImageFunc: func(ctx context.Context, contentHash string, s3Key string, fileSize int64, mimeType string, width *int, height *int) (*queries.OriginalImage, error) {
//				panic("mock out the CreateOriginalImage method")
//			},
//			DecrementReferenceCountFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DecrementReferenceCount method")
//			},
//			DeleteOriginalImageFunc: func(ctx context.Context, id string) error {
//				panic("mock out the DeleteOriginalImage method")
//			},
//			GetOriginalImageByHashFunc: func(ctx context.Context, contentHash string) (*queries.OriginalImage, error) {
//				panic("mock out the GetOriginalImageByHash method")
//			},
//			GetOriginalImageByIDFunc: func(ctx context.Context, id string) (*queries.OriginalImage, error) {
//				panic("mock out the GetOriginalImageByID method")
//			},
//			GetOriginalImageStatsFunc: func(ctx context.Context) (*OriginalImageStats, error) {
//				panic("mock out the GetOriginalImageStats method")
//			},
//			IncrementReferenceCountFunc: func(ctx context.Context, id string) error {
//				panic("mock out the IncrementReferenceCount method")
//			},
//			ListOrphanedOriginalImagesFunc: func(ctx context.Context, olderThan time.Duration, limit int) ([]*queries.OriginalImage, error) {
//				panic("mock out the ListOrphanedOriginalImages method")
//			},
//		}
//
//		// use mockedRepository in code that requires Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// CreateOriginalImageFunc mocks the CreateOriginalImage method.
	CreateOriginalImageFunc func(ctx context.Context, contentHash string, s3Key string, fileSize int64, mimeType string, width *int, height *int) (*queries.OriginalImage, error)

	// DecrementReferenceCountFunc mocks the DecrementReferenceCount method.
	DecrementReferenceCountFunc func(ctx context.Context, id string) error

	// DeleteOriginalImageFunc mocks the DeleteOriginalImage method.
	DeleteOriginalImageFunc func(ctx context.Context, id string) error

	// GetOriginalImageByHashFunc mocks the GetOriginalImageByHash method.
	GetOriginalImageByHashFunc func(ctx context.Context, contentHash string) (*queries.OriginalImage, error)

	// GetOriginalImageByIDFunc mocks the GetOriginalImageByID method.
	GetOriginalImageByIDFunc func(ctx context.Context, id string) (*queries.OriginalImage, error)

	// GetOriginalImageStatsFunc mocks the GetOriginalImageStats method.
	GetOriginalImageStatsFunc func(ctx context.Context) (*OriginalImageStats, error)

	// IncrementReferenceCountFunc mocks the IncrementReferenceCount method.
	IncrementReferenceCountFunc func(ctx context.Context, id string) error

	// ListOrphanedOriginalImagesFunc mocks the ListOrphanedOriginalImages method.
	ListOrphanedOriginalImagesFunc func(ctx context.Context, olderThan time.Duration, limit int) ([]*queries.OriginalImage, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateOriginalImage holds details about calls to the CreateOriginalImage method.
		CreateOriginalImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContentHash is the contentHash argument value.
			ContentHash string
			// S3Key is the s3Key argument value.
			S3Key string
			// FileSize is the fileSize argument value.
			FileSize int64
			// MimeType is the mimeType argument value.
			MimeType string
			// Width is the width argument value.
			Width *int
			// Height is the height argument value.
			Height *int
		}
		// DecrementReferenceCount holds details about calls to the DecrementReferenceCount method.
		DecrementReferenceCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// DeleteOriginalImage holds details about calls to the DeleteOriginalImage method.
		DeleteOriginalImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetOriginalImageByHash holds details about calls to the GetOriginalImageByHash method.
		GetOriginalImageByHash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContentHash is the contentHash argument value.
			ContentHash string
		}
		// GetOriginalImageByID holds details about calls to the GetOriginalImageByID method.
		GetOriginalImageByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// GetOriginalImageStats holds details about calls to the GetOriginalImageStats method.
		GetOriginalImageStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IncrementReferenceCount holds details about calls to the IncrementReferenceCount method.
		IncrementReferenceCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// ListOrphanedOriginalImages holds details about calls to the ListOrphanedOriginalImages method.
		ListOrphanedOriginalImages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OlderThan is the olderThan argument value.
			OlderThan time.Duration
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCreateOriginalImage        sync.RWMutex
	lockDecrementReferenceCount    sync.RWMutex
	lockDeleteOriginalImage        sync.RWMutex
	lockGetOriginalImageByHash     sync.RWMutex
	lockGetOriginalImageByID       sync.RWMutex
	lockGetOriginalImageStats      sync.RWMutex
	lockIncrementReferenceCount    sync.RWMutex
	lockListOrphanedOriginalImages sync.RWMutex
}

// CreateOriginalImage calls CreateOriginalImageFunc.
func (mock *RepositoryMock) CreateOriginalImage(ctx context.Context, contentHash string, s3Key string, fileSize int64, mimeType string, width *int, height *int) (*queries.OriginalImage, error) {
	if mock.CreateOriginalImageFunc == nil {
		panic("RepositoryMock.CreateOriginalImageFunc: method is nil but Repository.CreateOriginalImage was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ContentHash string
		S3Key       string
		FileSize    int64
		MimeType    string
		Width       *int
		Height      *int
	}{
		Ctx:         ctx,
		ContentHash: contentHash,
		S3Key:       s3Key,
		FileSize:    fileSize,
		MimeType:    mimeType,
		Width:       width,
		Height:      height,
	}
	mock.lockCreateOriginalImage.Lock()
	mock.calls.CreateOriginalImage = append(mock.calls.CreateOriginalImage, callInfo)
	mock.lockCreateOriginalImage.Unlock()
	return mock.CreateOriginalImageFunc(ctx, contentHash, s3Key, fileSize, mimeType, width, height)
}

// CreateOriginalImageCalls gets all the calls that were made to CreateOriginalImage.
// Check the length with:
//
//	len(mockedRepository.CreateOriginalImageCalls())
func (mock *RepositoryMock) CreateOriginalImageCalls() []struct {
	Ctx         context.Context
	ContentHash string
	S3Key       string
	FileSize    int64
	MimeType    string
	Width       *int
	Height      *int
} {
	var calls []struct {
		Ctx         context.Context
		ContentHash string
		S3Key       string
		FileSize    int64
		MimeType    string
		Width       *int
		Height      *int
	}
	mock.lockCreateOriginalImage.RLock()
	calls = mock.calls.CreateOriginalImage
	mock.lockCreateOriginalImage.RUnlock()
	return calls
}

// DecrementReferenceCount calls DecrementReferenceCountFunc.
func (mock *RepositoryMock) DecrementReferenceCount(ctx context.Context, id string) error {
	if mock.DecrementReferenceCountFunc == nil {
		panic("RepositoryMock.DecrementReferenceCountFunc: method is nil but Repository.DecrementReferenceCount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDecrementReferenceCount.Lock()
	mock.calls.DecrementReferenceCount = append(mock.calls.DecrementReferenceCount, callInfo)
	mock.lockDecrementReferenceCount.Unlock()
	return mock.DecrementReferenceCountFunc(ctx, id)
}

// DecrementReferenceCountCalls gets all the calls that were made to DecrementReferenceCount.
// Check the length with:
//
//	len(mockedRepository.DecrementReferenceCountCalls())
func (mock *RepositoryMock) DecrementReferenceCountCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDecrementReferenceCount.RLock()
	calls = mock.calls.DecrementReferenceCount
	mock.lockDecrementReferenceCount.RUnlock()
	return calls
}

// DeleteOriginalImage calls DeleteOriginalImageFunc.
func (mock *RepositoryMock) DeleteOriginalImage(ctx context.Context, id string) error {
	if mock.DeleteOriginalImageFunc == nil {
		panic("RepositoryMock.DeleteOriginalImageFunc: method is nil but Repository.DeleteOriginalImage was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteOriginalImage.Lock()
	mock.calls.DeleteOriginalImage = append(mock.calls.DeleteOriginalImage, callInfo)
	mock.lockDeleteOriginalImage.Unlock()
	return mock.DeleteOriginalImageFunc(ctx, id)
}

// DeleteOriginalImageCalls gets all the calls that were made to DeleteOriginalImage.
// Check the length with:
//
//	len(mockedRepository.DeleteOriginalImageCalls())
func (mock *RepositoryMock) DeleteOriginalImageCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDeleteOriginalImage.RLock()
	calls = mock.calls.DeleteOriginalImage
	mock.lockDeleteOriginalImage.RUnlock()
	return calls
}

// GetOriginalImageByHash calls GetOriginalImageByHashFunc.
func (mock *RepositoryMock) GetOriginalImageByHash(ctx context.Context, contentHash string) (*queries.OriginalImage, error) {
	if mock.GetOriginalImageByHashFunc == nil {
		panic("RepositoryMock.GetOriginalImageByHashFunc: method is nil but Repository.GetOriginalImageByHash was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ContentHash string
	}{
		Ctx:         ctx,
		ContentHash: contentHash,
	}
	mock.lockGetOriginalImageByHash.Lock()
	mock.calls.GetOriginalImageByHash = append(mock.calls.GetOriginalImageByHash, callInfo)
	mock.lockGetOriginalImageByHash.Unlock()
	return mock.GetOriginalImageByHashFunc(ctx, contentHash)
}

// GetOriginalImageByHashCalls gets all the calls that were made to GetOriginalImageByHash.
// Check the length with:
//
//	len(mockedRepository.GetOriginalImageByHashCalls())
func (mock *RepositoryMock) GetOriginalImageByHashCalls() []struct {
	Ctx         context.Context
	ContentHash string
} {
	var calls []struct {
		Ctx         context.Context
		ContentHash string
	}
	mock.lockGetOriginalImageByHash.RLock()
	calls = mock.calls.GetOriginalImageByHash
	mock.lockGetOriginalImageByHash.RUnlock()
	return calls
}

// GetOriginalImageByID calls GetOriginalImageByIDFunc.
func (mock *RepositoryMock) GetOriginalImageByID(ctx context.Context, id string) (*queries.OriginalImage, error) {
	if mock.GetOriginalImageByIDFunc == nil {
		panic("RepositoryMock.GetOriginalImageByIDFunc: method is nil but Repository.GetOriginalImageByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetOriginalImageByID.Lock()
	mock.calls.GetOriginalImageByID = append(mock.calls.GetOriginalImageByID, callInfo)
	mock.lockGetOriginalImageByID.Unlock()
	return mock.GetOriginalImageByIDFunc(ctx, id)
}

// GetOriginalImageByIDCalls gets all the calls that were made to GetOriginalImageByID.
// Check the length with:
//
//	len(mockedRepository.GetOriginalImageByIDCalls())
func (mock *RepositoryMock) GetOriginalImageByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetOriginalImageByID.RLock()
	calls = mock.calls.GetOriginalImageByID
	mock.lockGetOriginalImageByID.RUnlock()
	return calls
}

// GetOriginalImageStats calls GetOriginalImageStatsFunc.
func (mock *RepositoryMock) GetOriginalImageStats(ctx context.Context) (*OriginalImageStats, error) {
	if mock.GetOriginalImageStatsFunc == nil {
		panic("RepositoryMock.GetOriginalImageStatsFunc: method is nil but Repository.GetOriginalImageStats was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetOriginalImageStats.Lock()
	mock.calls.GetOriginalImageStats = append(mock.calls.GetOriginalImageStats, callInfo)
	mock.lockGetOriginalImageStats.Unlock()
	return mock.GetOriginalImageStatsFunc(ctx)
}

// GetOriginalImageStatsCalls gets all the calls that were made to GetOriginalImageStats.
// Check the length with:
//
//	len(mockedRepository.GetOriginalImageStatsCalls())
func (mock *RepositoryMock) GetOriginalImageStatsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetOriginalImageStats.RLock()
	calls = mock.calls.GetOriginalImageStats
	mock.lockGetOriginalImageStats.RUnlock()
	return calls
}

// IncrementReferenceCount calls IncrementReferenceCountFunc.
func (mock *RepositoryMock) IncrementReferenceCount(ctx context.Context, id string) error {
	if mock.IncrementReferenceCountFunc == nil {
		panic("RepositoryMock.IncrementReferenceCountFunc: method is nil but Repository.IncrementReferenceCount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockIncrementReferenceCount.Lock()
	mock.calls.IncrementReferenceCount = append(mock.calls.IncrementReferenceCount, callInfo)
	mock.lockIncrementReferenceCount.Unlock()
	return mock.IncrementReferenceCountFunc(ctx, id)
}

// IncrementReferenceCountCalls gets all the calls that were made to IncrementReferenceCount.
// Check the length with:
//
//	len(mockedRepository.IncrementReferenceCountCalls())
func (mock *RepositoryMock) IncrementReferenceCountCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockIncrementReferenceCount.RLock()
	calls = mock.calls.IncrementReferenceCount
	mock.lockIncrementReferenceCount.RUnlock()
	return calls
}

// ListOrphanedOriginalImages calls ListOrphanedOriginalImagesFunc.
func (mock *RepositoryMock) ListOrphanedOriginalImages(ctx context.Context, olderThan time.Duration, limit int) ([]*queries.OriginalImage, error) {
	if mock.ListOrphanedOriginalImagesFunc == nil {
		panic("RepositoryMock.ListOrphanedOriginalImagesFunc: method is nil but Repository.ListOrphanedOriginalImages was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		OlderThan time.Duration
		Limit     int
	}{
		Ctx:       ctx,
		OlderThan: olderThan,
		Limit:     limit,
	}
	mock.lockListOrphanedOriginalImages.Lock()
	mock.calls.ListOrphanedOriginalImages = append(mock.calls.ListOrphanedOriginalImages, callInfo)
	mock.lockListOrphanedOriginalImages.Unlock()
	return mock.ListOrphanedOriginalImagesFunc(ctx, olderThan, limit)
}

// ListOrphanedOriginalImagesCalls gets all the calls that were made to ListOrphanedOriginalImages.
// Check the length with:
//
//	len(mockedRepository.ListOrphanedOriginalImagesCalls())
func (mock *RepositoryMock) ListOrphanedOriginalImagesCalls() []struct {
	Ctx       context.Context
	OlderThan time.Duration
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		OlderThan time.Duration
		Limit     int
	}
	mock.lockListOrphanedOriginalImages.RLock()
	calls = mock.calls.ListOrphanedOriginalImages
	mock.lockListOrphanedOriginalImages.RUnlock()
	return calls
}
