// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package billing

import (
	"context"
	"sync"
)

// Ensure, that SubscriptionCheckerMock does implement SubscriptionChecker.
// If this is not the case, regenerate this file with moq.
var _ SubscriptionChecker = &SubscriptionCheckerMock{}

// SubscriptionCheckerMock is a mock implementation of SubscriptionChecker.
//
//	func TestSomethingThatUsesSubscriptionChecker(t *testing.T) {
//
//		// make and configure a mocked SubscriptionChecker
//		mockedSubscriptionChecker := &SubscriptionCheckerMock{
//			HasActiveSubscriptionFunc: func(ctx context.Context, userID string) (bool, error) {
//				panic("mock out the HasActiveSubscription method")
//			},
//		}
//
//		// use mockedSubscriptionChecker in code that requires SubscriptionChecker
//		// and then make assertions.
//
//	}
type SubscriptionCheckerMock struct {
	// HasActiveSubscriptionFunc mocks the HasActiveSubscription method.
	HasActiveSubscriptionFunc func(ctx context.Context, userID string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// HasActiveSubscription holds details about calls to the HasActiveSubscription method.
		HasActiveSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockHasActiveSubscription sync.RWMutex
}

// HasActiveSubscription calls HasActiveSubscriptionFunc.
func (mock *SubscriptionCheckerMock) HasActiveSubscription(ctx context.Context, userID string) (bool, error) {
	if mock.HasActiveSubscriptionFunc == nil {
		panic("SubscriptionCheckerMock.HasActiveSubscriptionFunc: method is nil but SubscriptionChecker.HasActiveSubscription was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockHasActiveSubscription.Lock()
	mock.calls.HasActiveSubscription = append(mock.calls.HasActiveSubscription, callInfo)
	mock.lockHasActiveSubscription.Unlock()
	return mock.HasActiveSubscriptionFunc(ctx, userID)
}

// HasActiveSubscriptionCalls gets all the calls that were made to HasActiveSubscription.
// Check the length with:
//
//	len(mockedSubscriptionChecker.HasActiveSubscriptionCalls())
func (mock *SubscriptionCheckerMock) HasActiveSubscriptionCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockHasActiveSubscription.RLock()
	calls = mock.calls.HasActiveSubscription
	mock.lockHasActiveSubscription.RUnlock()
	return calls
}
