// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package billing

import (
	"context"
	"sync"
)

// Ensure, that UsageServiceMock does implement UsageService.
// If this is not the case, regenerate this file with moq.
var _ UsageService = &UsageServiceMock{}

// UsageServiceMock is a mock implementation of UsageService.
//
//	func TestSomethingThatUsesUsageService(t *testing.T) {
//
//		// make and configure a mocked UsageService
//		mockedUsageService := &UsageServiceMock{
//			CanCreateImageFunc: func(ctx context.Context, userID string) (bool, error) {
//				panic("mock out the CanCreateImage method")
//			},
//			GetPlanByCodeFunc: func(ctx context.Context, code string) (*PlanInfo, error) {
//				panic("mock out the GetPlanByCode method")
//			},
//			GetUsageFunc: func(ctx context.Context, userID string) (*UsageStats, error) {
//				panic("mock out the GetUsage method")
//			},
//		}
//
//		// use mockedUsageService in code that requires UsageService
//		// and then make assertions.
//
//	}
type UsageServiceMock struct {
	// CanCreateImageFunc mocks the CanCreateImage method.
	CanCreateImageFunc func(ctx context.Context, userID string) (bool, error)

	// GetPlanByCodeFunc mocks the GetPlanByCode method.
	GetPlanByCodeFunc func(ctx context.Context, code string) (*PlanInfo, error)

	// GetUsageFunc mocks the GetUsage method.
	GetUsageFunc func(ctx context.Context, userID string) (*UsageStats, error)

	// calls tracks calls to the methods.
	calls struct {
		// CanCreateImage holds details about calls to the CanCreateImage method.
		CanCreateImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
		// GetPlanByCode holds details about calls to the GetPlanByCode method.
		GetPlanByCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// GetUsage holds details about calls to the GetUsage method.
		GetUsage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockCanCreateImage sync.RWMutex
	lockGetPlanByCode  sync.RWMutex
	lockGetUsage       sync.RWMutex
}

// CanCreateImage calls CanCreateImageFunc.
func (mock *UsageServiceMock) CanCreateImage(ctx context.Context, userID string) (bool, error) {
	if mock.CanCreateImageFunc == nil {
		panic("UsageServiceMock.CanCreateImageFunc: method is nil but UsageService.CanCreateImage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockCanCreateImage.Lock()
	mock.calls.CanCreateImage = append(mock.calls.CanCreateImage, callInfo)
	mock.lockCanCreateImage.Unlock()
	return mock.CanCreateImageFunc(ctx, userID)
}

// CanCreateImageCalls gets all the calls that were made to CanCreateImage.
// Check the length with:
//
//	len(mockedUsageService.CanCreateImageCalls())
func (mock *UsageServiceMock) CanCreateImageCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockCanCreateImage.RLock()
	calls = mock.calls.CanCreateImage
	mock.lockCanCreateImage.RUnlock()
	return calls
}

// GetPlanByCode calls GetPlanByCodeFunc.
func (mock *UsageServiceMock) GetPlanByCode(ctx context.Context, code string) (*PlanInfo, error) {
	if mock.GetPlanByCodeFunc == nil {
		panic("UsageServiceMock.GetPlanByCodeFunc: method is nil but UsageService.GetPlanByCode was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockGetPlanByCode.Lock()
	mock.calls.GetPlanByCode = append(mock.calls.GetPlanByCode, callInfo)
	mock.lockGetPlanByCode.Unlock()
	return mock.GetPlanByCodeFunc(ctx, code)
}

// GetPlanByCodeCalls gets all the calls that were made to GetPlanByCode.
// Check the length with:
//
//	len(mockedUsageService.GetPlanByCodeCalls())
func (mock *UsageServiceMock) GetPlanByCodeCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockGetPlanByCode.RLock()
	calls = mock.calls.GetPlanByCode
	mock.lockGetPlanByCode.RUnlock()
	return calls
}

// GetUsage calls GetUsageFunc.
func (mock *UsageServiceMock) GetUsage(ctx context.Context, userID string) (*UsageStats, error) {
	if mock.GetUsageFunc == nil {
		panic("UsageServiceMock.GetUsageFunc: method is nil but UsageService.GetUsage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetUsage.Lock()
	mock.calls.GetUsage = append(mock.calls.GetUsage, callInfo)
	mock.lockGetUsage.Unlock()
	return mock.GetUsageFunc(ctx, userID)
}

// GetUsageCalls gets all the calls that were made to GetUsage.
// Check the length with:
//
//	len(mockedUsageService.GetUsageCalls())
func (mock *UsageServiceMock) GetUsageCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockGetUsage.RLock()
	calls = mock.calls.GetUsage
	mock.lockGetUsage.RUnlock()
	return calls
}
