// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package image

import (
	"context"
	"sync"
)

// Ensure, that UsageCheckerMock does implement UsageChecker.
// If this is not the case, regenerate this file with moq.
var _ UsageChecker = &UsageCheckerMock{}

// UsageCheckerMock is a mock implementation of UsageChecker.
//
//	func TestSomethingThatUsesUsageChecker(t *testing.T) {
//
//		// make and configure a mocked UsageChecker
//		mockedUsageChecker := &UsageCheckerMock{
//			CanCreateImageFunc: func(ctx context.Context, userID string) (bool, error) {
//				panic("mock out the CanCreateImage method")
//			},
//		}
//
//		// use mockedUsageChecker in code that requires UsageChecker
//		// and then make assertions.
//
//	}
type UsageCheckerMock struct {
	// CanCreateImageFunc mocks the CanCreateImage method.
	CanCreateImageFunc func(ctx context.Context, userID string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// CanCreateImage holds details about calls to the CanCreateImage method.
		CanCreateImage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID string
		}
	}
	lockCanCreateImage sync.RWMutex
}

// CanCreateImage calls CanCreateImageFunc.
func (mock *UsageCheckerMock) CanCreateImage(ctx context.Context, userID string) (bool, error) {
	if mock.CanCreateImageFunc == nil {
		panic("UsageCheckerMock.CanCreateImageFunc: method is nil but UsageChecker.CanCreateImage was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID string
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockCanCreateImage.Lock()
	mock.calls.CanCreateImage = append(mock.calls.CanCreateImage, callInfo)
	mock.lockCanCreateImage.Unlock()
	return mock.CanCreateImageFunc(ctx, userID)
}

// CanCreateImageCalls gets all the calls that were made to CanCreateImage.
// Check the length with:
//
//	len(mockedUsageChecker.CanCreateImageCalls())
func (mock *UsageCheckerMock) CanCreateImageCalls() []struct {
	Ctx    context.Context
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		UserID string
	}
	mock.lockCanCreateImage.RLock()
	calls = mock.calls.CanCreateImage
	mock.lockCanCreateImage.RUnlock()
	return calls
}
